#!/usr/bin/env python3
"""
human-readable: Generate a single self-contained HTML viewer from a folder of Markdown files.

Usage:
    python generate.py                      # use .human-readable.yml; first run is interactive
    python generate.py path/to/docs         # one-off override of source path
    python generate.py --watch              # rebuild on MD/image change (needs: pip install watchdog)
    python generate.py --help               # show this message
"""
from __future__ import annotations

import argparse
import base64
import fnmatch
import json
import mimetypes
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

try:
    import yaml  # PyYAML, optional
    HAS_YAML = True
except ImportError:
    HAS_YAML = False

SKILL_DIR = Path(__file__).resolve().parent.parent
LIB_DIR = SKILL_DIR / "assets" / "lib"
FONT_DIR = LIB_DIR / "fonts"
TEMPLATE_DIR = SKILL_DIR / "assets" / "template"

FONT_FILES = {
    "font_fraunces_regular": "Fraunces-Variable.woff2",
    "font_fraunces_italic": "Fraunces-Italic-Variable.woff2",
    "font_plex_regular": "IBMPlexSans-Regular.woff2",
    "font_plex_italic": "IBMPlexSans-Italic.woff2",
    "font_plex_medium": "IBMPlexSans-Medium.woff2",
    "font_plex_semibold": "IBMPlexSans-SemiBold.woff2",
    "font_jb_regular": "JetBrainsMono-Regular.woff2",
    "font_jb_semibold": "JetBrainsMono-SemiBold.woff2",
}


def build_font_data_uri(filename: str) -> str:
    """Read a woff2 file and return a data: URI suitable for use inside CSS url(...)."""
    path = FONT_DIR / filename
    if not path.exists():
        return ""
    b64 = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:font/woff2;base64,{b64}"


CONFIG_FILENAME = ".human-readable.yml"
DEFAULT_OUTPUT = "./human-readable.html"
CANDIDATE_DIRS = ["docs", "documentation", "wiki", "notes", "guides", "doc", "site"]
DEFAULT_EXCLUDES = ["**/node_modules/**", "**/.git/**", "**/dist/**", "**/build/**"]

# ===== logging =====
def info(msg: str) -> None: print(f"  {msg}", flush=True)
def step(msg: str) -> None: print(f"▸ {msg}", flush=True)
def warn(msg: str) -> None: print(f"⚠  {msg}", file=sys.stderr, flush=True)
def err(msg: str) -> None: print(f"✗  {msg}", file=sys.stderr, flush=True)


# ===== config =====
def parse_simple_yaml(text: str) -> dict:
    """Tiny YAML reader for our flat config; only handles what we write."""
    cfg: dict = {}
    current_list_key: str | None = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        if line.startswith("  - "):
            if current_list_key:
                val = line[4:].strip().strip('"').strip("'")
                cfg[current_list_key].append(val)
            continue
        current_list_key = None
        if ":" not in line:
            continue
        key, _, rest = line.partition(":")
        key = key.strip()
        rest = rest.strip()
        if rest == "" or rest == "[]":
            cfg[key] = []
            current_list_key = key
        elif rest in ("null", "~", ""):
            cfg[key] = None
        elif rest.lower() == "true":
            cfg[key] = True
        elif rest.lower() == "false":
            cfg[key] = False
        else:
            cfg[key] = rest.strip('"').strip("'")
    return cfg


def load_config(repo_root: Path) -> dict | None:
    cfg_path = repo_root / CONFIG_FILENAME
    if not cfg_path.exists():
        return None
    text = cfg_path.read_text()
    if HAS_YAML:
        return yaml.safe_load(text) or {}
    return parse_simple_yaml(text)


def write_config(repo_root: Path, cfg: dict) -> None:
    lines = [
        "# human-readable config — generated by the skill.",
        "# Edit freely; re-run `python generate.py` to apply.",
        "",
        f"source: {cfg['source']}",
        f"output: {cfg['output']}",
        f"title: {cfg['title'] if cfg['title'] is not None else 'null'}",
        "excludes:",
    ]
    for ex in cfg.get("excludes", []):
        lines.append(f'  - "{ex}"')
    lines.append(f"gitignore_output: {'true' if cfg.get('gitignore_output', True) else 'false'}")
    lines.append(f"hooks_installed: {'true' if cfg.get('hooks_installed', False) else 'false'}")
    lines.append(f"theme_default: {cfg.get('theme_default', 'light')}")
    (repo_root / CONFIG_FILENAME).write_text("\n".join(lines) + "\n")


# ===== repo helpers =====
def find_repo_root(start: Path) -> Path:
    cur = start.resolve()
    while cur != cur.parent:
        if (cur / ".git").exists() or (cur / CONFIG_FILENAME).exists():
            return cur
        cur = cur.parent
    return start.resolve()


def derive_title(repo_root: Path, config_title: str | None) -> str:
    if config_title:
        return config_title
    try:
        result = subprocess.run(
            ["git", "-C", str(repo_root), "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True, timeout=3
        )
        return Path(result.stdout.strip()).name
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        return repo_root.name


# ===== discovery =====
def discover_source(repo_root: Path) -> list[tuple[Path, int]]:
    candidates: list[tuple[Path, int]] = []
    for name in CANDIDATE_DIRS:
        p = repo_root / name
        if p.is_dir():
            count = sum(1 for _ in p.rglob("*.md"))
            if count > 0:
                candidates.append((p, count))
    if not candidates:
        # Find any folder with MD files; pick top 3 by count.
        counts: dict[Path, int] = {}
        for md in repo_root.rglob("*.md"):
            if any(part.startswith(".") for part in md.relative_to(repo_root).parts):
                continue
            counts[md.parent] = counts.get(md.parent, 0) + 1
        candidates = sorted(counts.items(), key=lambda x: x[1], reverse=True)[:3]
    return candidates


def first_run_interactive(repo_root: Path) -> dict:
    print()
    step(f"First run in {repo_root}")
    print(f"  No {CONFIG_FILENAME} found. Let's set one up.")
    print()
    cands = discover_source(repo_root)
    if not cands:
        err("No .md files found anywhere under the repo. Aborting.")
        sys.exit(1)
    print("  Candidate doc folders (by MD file count):")
    for i, (p, n) in enumerate(cands[:5], 1):
        rel = p.relative_to(repo_root)
        print(f"    {i}) {rel}  ({n} files)")
    print(f"    {len(cands[:5]) + 1}) (other — type a path)")
    print()
    while True:
        choice = input(f"  Choose source [1-{len(cands[:5]) + 1}, default 1]: ").strip() or "1"
        try:
            idx = int(choice)
            if 1 <= idx <= len(cands[:5]):
                source = cands[idx - 1][0].relative_to(repo_root)
                break
            if idx == len(cands[:5]) + 1:
                custom = input("  Path (relative to repo root): ").strip()
                source = Path(custom)
                if not (repo_root / source).is_dir():
                    err(f"  {source} is not a directory.")
                    continue
                break
        except ValueError:
            pass
        err("  Invalid choice.")
    print()
    output = input(f"  Output path [{DEFAULT_OUTPUT}]: ").strip() or DEFAULT_OUTPUT
    print()
    gi = input("  Add output to .gitignore (recommended)? [Y/n]: ").strip().lower()
    gitignore_output = gi != "n"
    print()
    hk = input("  Install git hooks (post-merge + post-checkout) to auto-rebuild? [y/N]: ").strip().lower()
    install_hooks = hk == "y"

    cfg = {
        "source": str(source),
        "output": output,
        "title": None,
        "excludes": list(DEFAULT_EXCLUDES),
        "gitignore_output": gitignore_output,
        "hooks_installed": False,
        "theme_default": "light",
    }
    write_config(repo_root, cfg)
    info(f"Wrote {repo_root / CONFIG_FILENAME}")

    if gitignore_output:
        append_to_gitignore(repo_root, output)
    if install_hooks:
        ok = install_git_hooks(repo_root)
        cfg["hooks_installed"] = ok
        write_config(repo_root, cfg)
    return cfg


def append_to_gitignore(repo_root: Path, output: str) -> None:
    gi = repo_root / ".gitignore"
    entry = output.lstrip("./")
    existing = gi.read_text() if gi.exists() else ""
    if entry in existing.splitlines():
        return
    with gi.open("a") as f:
        if existing and not existing.endswith("\n"):
            f.write("\n")
        f.write(f"# human-readable generator output\n{entry}\n")
    info(f"Added {entry} to .gitignore")


def install_git_hooks(repo_root: Path) -> bool:
    hooks_dir = repo_root / ".git" / "hooks"
    if not hooks_dir.is_dir():
        warn("No .git/hooks directory — skipping hook install.")
        return False
    script = (
        "#!/usr/bin/env bash\n"
        "# Installed by the human-readable skill.\n"
        "set -e\n"
        f'python "{Path(__file__).resolve()}" >/dev/null 2>&1 || true\n'
    )
    for name in ("post-merge", "post-checkout"):
        hook = hooks_dir / name
        if hook.exists():
            warn(f"{name} already exists — leaving it alone.")
            continue
        hook.write_text(script)
        hook.chmod(0o755)
        info(f"Installed {hook}")
    return True


# ===== source walk =====
def matches_any(path: Path, source_root: Path, patterns: list[str]) -> bool:
    rel = str(path.relative_to(source_root))
    for pat in patterns:
        if fnmatch.fnmatch(rel, pat):
            return True
        if fnmatch.fnmatch(path.name, pat):
            return True
    return False


def load_gitignore_patterns(repo_root: Path) -> list[str]:
    gi = repo_root / ".gitignore"
    if not gi.exists():
        return []
    pats: list[str] = []
    for raw in gi.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        # Convert simple gitignore patterns into fnmatch globs.
        pats.append(line.lstrip("/"))
        if line.endswith("/"):
            pats.append(line.rstrip("/") + "/**")
    return pats


def walk_md_files(source_root: Path, repo_root: Path, excludes: list[str]) -> list[Path]:
    gi_pats = load_gitignore_patterns(repo_root)
    all_excludes = list(excludes) + gi_pats
    md_files: list[Path] = []
    for md in source_root.rglob("*.md"):
        if any(part.startswith(".") for part in md.relative_to(source_root).parts):
            continue
        if matches_any(md, source_root, all_excludes):
            continue
        md_files.append(md)
    return md_files


# ===== frontmatter =====
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)

def parse_frontmatter(text: str) -> tuple[dict, str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    raw = m.group(1)
    body = text[m.end():]
    if HAS_YAML:
        try:
            data = yaml.safe_load(raw) or {}
            if isinstance(data, dict):
                return data, body
        except Exception:
            pass
    # Fallback: parse simple key: value pairs.
    data: dict = {}
    for line in raw.splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            data[k.strip()] = v.strip().strip('"').strip("'")
    return data, body


# ===== images =====
IMG_RE = re.compile(r"!\[([^\]]*)\]\(([^)\s]+)(\s+\"[^\"]*\")?\)")

def base64_inline_images(md_text: str, md_path: Path, source_root: Path) -> str:
    def repl(m: re.Match) -> str:
        alt = m.group(1)
        href = m.group(2)
        title = m.group(3) or ""
        # Skip remote and data URIs.
        if href.startswith(("http://", "https://", "data:")):
            return m.group(0)
        # Resolve relative to MD file's directory.
        target = (md_path.parent / href).resolve()
        if not target.exists():
            return m.group(0)
        try:
            target.relative_to(source_root.resolve())
        except ValueError:
            # Image outside the source tree — still embed if it's nearby in repo.
            pass
        mime, _ = mimetypes.guess_type(target.name)
        if not mime or not mime.startswith("image/"):
            return m.group(0)
        try:
            b64 = base64.b64encode(target.read_bytes()).decode("ascii")
        except OSError:
            return m.group(0)
        return f"![{alt}](data:{mime};base64,{b64}{title})"
    return IMG_RE.sub(repl, md_text)


# ===== plantuml =====
PLANTUML_RE = re.compile(r"^```plantuml\s*\n(.*?)\n```", re.DOTALL | re.MULTILINE)

def render_plantuml(md_text: str) -> str:
    matches = list(PLANTUML_RE.finditer(md_text))
    if not matches:
        return md_text
    if shutil.which("plantuml") is None:
        err(
            "PlantUML diagrams found but the `plantuml` binary is not on PATH.\n"
            "  Install it and re-run:\n"
            "    macOS:    brew install plantuml\n"
            "    Debian:   sudo apt install plantuml\n"
            "    Other:    https://plantuml.com/download\n"
            "  Or remove the ```plantuml blocks from your docs."
        )
        sys.exit(2)
    out = md_text
    # Replace from end to start so offsets stay valid.
    for m in reversed(matches):
        src = m.group(1)
        try:
            result = subprocess.run(
                ["plantuml", "-tsvg", "-pipe"],
                input=src, capture_output=True, text=True, timeout=30
            )
        except subprocess.TimeoutExpired:
            warn("plantuml timed out on a block; leaving raw.")
            continue
        if result.returncode != 0 or not result.stdout:
            warn(f"plantuml failed: {result.stderr.strip()[:120]}")
            continue
        # Strip XML decl if present; marked passes through raw HTML.
        svg = result.stdout
        svg = re.sub(r"^<\?xml[^>]+\?>\s*", "", svg)
        replacement = f"\n<div class=\"plantuml-rendered\">{svg}</div>\n"
        out = out[:m.start()] + replacement + out[m.end():]
    return out


def has_plantuml(md_files: list[Path]) -> bool:
    for f in md_files:
        try:
            text = f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if PLANTUML_RE.search(text):
            return True
    return False


# ===== tree =====
def build_tree(md_files: list[Path], source_root: Path, content: dict) -> dict:
    root = {"type": "folder", "path": "", "children": {}}
    for md in md_files:
        rel = md.relative_to(source_root)
        parts = rel.parts
        cur = root
        accum: list[str] = []
        for p in parts[:-1]:
            accum.append(p)
            children = cur["children"]
            if p not in children:
                children[p] = {
                    "type": "folder",
                    "path": "/".join(accum),
                    "children": {},
                }
            cur = children[p]
        leaf = parts[-1]
        path = "/".join(parts)
        cur["children"][leaf] = {
            "type": "file",
            "path": path,
            "title": content.get(path, {}).get("title") or leaf,
        }
    return root


# ===== title extraction =====
HEADING_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)

def extract_title(md_body: str, frontmatter: dict, filename: str) -> str:
    if frontmatter.get("title"):
        return str(frontmatter["title"])
    m = HEADING_RE.search(md_body)
    if m:
        return m.group(1).strip()
    return filename


# ===== inline-safe wrappers =====
def read_text(p: Path) -> str:
    return p.read_text(encoding="utf-8")


_CLOSE_SCRIPT_RE = re.compile(r"</(script)", re.IGNORECASE)

def inject_into_script(text: str) -> str:
    """Prevent </script> in user data from terminating our <script> tag.

    HTML closes script tags case-insensitively, so the match must too —
    a markdown example containing ``</SCRIPT>`` would otherwise terminate
    the JSON payload script tag and corrupt the viewer.
    """
    return _CLOSE_SCRIPT_RE.sub(r"<\\/\1", text)


# ===== build =====
def build(repo_root: Path, cfg: dict, source_override: Path | None = None) -> Path:
    source_rel = source_override if source_override else Path(cfg["source"])
    source_root = (repo_root / source_rel).resolve()
    if not source_root.is_dir():
        err(f"Source folder does not exist: {source_root}")
        sys.exit(1)

    step(f"Walking {source_root.relative_to(repo_root)}/")
    md_files = walk_md_files(source_root, repo_root, cfg.get("excludes", []))
    info(f"Found {len(md_files)} MD file(s)")

    if has_plantuml(md_files):
        if shutil.which("plantuml") is None:
            err(
                "PlantUML diagrams detected but the `plantuml` binary is missing on PATH.\n"
                "  Install it and re-run:\n"
                "    macOS:    brew install plantuml\n"
                "    Debian:   sudo apt install plantuml\n"
                "    Other:    https://plantuml.com/download"
            )
            sys.exit(2)

    step("Processing files (frontmatter, images, plantuml)")
    content: dict[str, dict] = {}
    for md in md_files:
        rel = md.relative_to(source_root).as_posix()
        try:
            raw = md.read_text(encoding="utf-8", errors="replace")
        except OSError as e:
            warn(f"Skipping {rel}: {e}")
            continue
        fm, body = parse_frontmatter(raw)
        body = base64_inline_images(body, md, source_root)
        body = render_plantuml(body)
        title = extract_title(body, fm, md.name)
        try:
            mtime = int(md.stat().st_mtime)
        except OSError:
            mtime = 0
        content[rel] = {
            "frontmatter": fm,
            "markdown": body,
            "title": title,
            "mtime": mtime,
        }

    step("Building directory tree")
    tree = build_tree(md_files, source_root, content)

    step("Loading template + libraries")
    shell = read_text(TEMPLATE_DIR / "shell.html")
    styles = read_text(TEMPLATE_DIR / "styles.css")
    app_js = read_text(TEMPLATE_DIR / "app.js")
    lib_marked = read_text(LIB_DIR / "marked.min.js")
    lib_mermaid = read_text(LIB_DIR / "mermaid.min.js")
    lib_katex_js = read_text(LIB_DIR / "katex.min.js")
    lib_katex_css = read_text(LIB_DIR / "katex.min.css")
    lib_katex_ar = read_text(LIB_DIR / "katex-auto-render.min.js")
    lib_hl_js = read_text(LIB_DIR / "highlight.min.js")
    lib_hl_light = read_text(LIB_DIR / "highlight-light.css")
    lib_hl_dark = read_text(LIB_DIR / "highlight-dark.css")

    # Inline web fonts into styles.css before they are baked into the HTML.
    for key, filename in FONT_FILES.items():
        styles = styles.replace(f"{{{{{key}}}}}", build_font_data_uri(filename))

    title = derive_title(repo_root, cfg.get("title"))
    theme_default = cfg.get("theme_default", "light")
    if theme_default not in ("light", "dark"):
        theme_default = "light"

    tree_json = inject_into_script(json.dumps(tree, ensure_ascii=False))
    content_json = inject_into_script(json.dumps(content, ensure_ascii=False))
    meta_json = inject_into_script(json.dumps({
        "title": title,
        "theme_default": theme_default,
    }, ensure_ascii=False))

    # Substitute placeholders. Use replace not format to avoid clashing with CSS/JS braces.
    out = shell
    substitutions = {
        "{{title}}": title,
        "{{theme_default}}": theme_default,
        "{{tree_json}}": tree_json,
        "{{content_json}}": content_json,
        "{{meta_json}}": meta_json,
        "{{styles}}": styles,
        "{{app_js}}": app_js,
        "{{lib_marked}}": lib_marked,
        "{{lib_mermaid}}": lib_mermaid,
        "{{lib_katex_js}}": lib_katex_js,
        "{{lib_katex_css}}": lib_katex_css,
        "{{lib_katex_auto_render}}": lib_katex_ar,
        "{{lib_highlight_js}}": lib_hl_js,
        "{{lib_highlight_light}}": lib_hl_light,
        "{{lib_highlight_dark}}": lib_hl_dark,
    }
    for placeholder, value in substitutions.items():
        out = out.replace(placeholder, value)

    output_path = (repo_root / cfg["output"]).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = output_path.with_suffix(output_path.suffix + ".tmp")
    tmp_path.write_text(out, encoding="utf-8")
    tmp_path.replace(output_path)

    size_mb = output_path.stat().st_size / 1024 / 1024
    step(f"Wrote {output_path.relative_to(repo_root) if output_path.is_relative_to(repo_root) else output_path} ({size_mb:.2f} MB)")
    info(f"Open with: open '{output_path}'  (macOS)   |   xdg-open '{output_path}' (Linux)")
    return output_path


# ===== watch =====
def watch(repo_root: Path, cfg: dict, source_override: Path | None) -> None:
    try:
        from watchdog.observers import Observer
        from watchdog.events import FileSystemEventHandler
    except ImportError:
        err("--watch requires the watchdog package: pip install watchdog")
        sys.exit(1)

    source_rel = source_override if source_override else Path(cfg["source"])
    source_root = (repo_root / source_rel).resolve()

    class Handler(FileSystemEventHandler):
        def __init__(self) -> None:
            self.last = 0.0

        def on_any_event(self, event) -> None:  # type: ignore[override]
            if event.is_directory:
                return
            ext = Path(event.src_path).suffix.lower()
            if ext not in (".md", ".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp"):
                return
            now = time.time()
            if now - self.last < 0.5:
                return
            self.last = now
            print()
            step(f"Change detected: {Path(event.src_path).name}")
            try:
                build(repo_root, cfg, source_override)
            except SystemExit:
                pass
            except Exception as e:
                err(f"Build failed: {e}")

    # Initial build.
    build(repo_root, cfg, source_override)
    step("Watching for changes (Ctrl-C to stop)…")
    obs = Observer()
    obs.schedule(Handler(), str(source_root), recursive=True)
    obs.start()
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        pass
    finally:
        obs.stop()
        obs.join()


# ===== main =====
def main() -> int:
    parser = argparse.ArgumentParser(
        prog="human-readable",
        description="Generate a single self-contained HTML viewer for a folder of Markdown files.",
    )
    parser.add_argument("source", nargs="?", default=None,
                        help="Optional source folder (overrides config for one run).")
    parser.add_argument("--watch", action="store_true",
                        help="Rebuild on file change (requires watchdog).")
    args = parser.parse_args()

    cwd = Path.cwd()
    repo_root = find_repo_root(cwd)
    source_override = Path(args.source) if args.source else None

    cfg = load_config(repo_root)
    if cfg is None:
        if not sys.stdin.isatty():
            err(f"No {CONFIG_FILENAME} in {repo_root} and stdin is not a TTY — cannot prompt interactively.")
            err("Run once in an interactive terminal, or create the config manually.")
            return 1
        cfg = first_run_interactive(repo_root)

    # Ensure all keys exist.
    cfg.setdefault("source", "docs")
    cfg.setdefault("output", DEFAULT_OUTPUT)
    cfg.setdefault("title", None)
    cfg.setdefault("excludes", list(DEFAULT_EXCLUDES))
    cfg.setdefault("gitignore_output", True)
    cfg.setdefault("hooks_installed", False)
    cfg.setdefault("theme_default", "light")

    if args.watch:
        watch(repo_root, cfg, source_override)
    else:
        build(repo_root, cfg, source_override)
    return 0


if __name__ == "__main__":
    sys.exit(main())
